language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix
